#!/usr/bin/env bash
# Seal an XRM private runtime blob — emits a MIND include file
# with the compile-time-baked SHA-256 fingerprint.
#
# Usage: ./seal_blob.sh <path-to-blob>
#
# The emitted include is consumed by the [protection] block in
# xrm_mind_port.mind; any byte change to the blob after sealing
# causes verify_blob_seal() to fail and the dispatch path to reject.

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <blob>" >&2
    exit 1
fi

BLOB="$1"
if [[ ! -f "$BLOB" ]]; then
    echo "ERROR: blob not found: $BLOB" >&2
    exit 1
fi

HASH=$(sha256sum "$BLOB" | awk '{print $1}')
SIZE=$(stat -c %s "$BLOB" 2>/dev/null || stat -f %z "$BLOB")
NAME=$(basename "$BLOB")

cat <<EOF
// seal_hashes.inc — generated by test-harness/seal_blob.sh
// DO NOT EDIT. Re-run the harness to regenerate.
// Blob:    $NAME
// Size:    $SIZE bytes
// Sealed:  $(date -u +%Y-%m-%dT%H:%M:%SZ)

const XRM_BLOB_SHA256: Hash256 = Hash256::from_hex("$HASH")
const XRM_BLOB_VERSION_TAG: Hash256 = Hash256::from_hex("$(printf '%s' "xrm-ssd.v23.3" | sha256sum | awk '{print $1}')")
EOF
